In [3]:
x = 1/3
print('x= ' + x)

TypeError: can only concatenate str (not "float") to str

In [4]:
# 문자열과 함께 사용하고 싶은 경우는 str을 같이 사용하기!
print('x = ' + str(x))

x = 0.3333333333333333


In [6]:
print('weight = {}kg'.format(x))
print('weight = {0}kg'.format(x)) # 숫자 넣어도 되고 안넣어도 되고

weight = 0.3333333333333333kg
weight = 0.3333333333333333kg


In [8]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight = {}kg , {}kg, {}kg'.format(x, y ,z))

weight = 0.3333333333333333kg , 0.14285714285714285kg, 0.25kg


In [9]:
print('weight = {1}kg, {2}kg, {0}kg'.format(x, y , z)) # 숫자 지정해서 원하는 위치 넣기

weight = 0.14285714285714285kg, 0.25kg, 0.3333333333333333kg


In [10]:
# 리스트 이용하기
x = [1, 1, 2, 3, 5]
print(x)

[1, 1, 2, 3, 5]


In [11]:
x[0] # 인덱스 표시할때는 []이안에 숫자넣기. 인덱스는 0부터 시작한다.

1

In [12]:
print(type(x))
print(type(x[0])) # 리스트안은 정수형

<class 'list'>
<class 'int'>


In [13]:
# 리스트 수정해보기
print(x)
x[3] = 100
print(x) # 인덱스 3인 4번째 자리가 100으로 바뀐것을 확인할 수 있음.

[1, 1, 2, 3, 5]
[1, 1, 2, 100, 5]


In [14]:
len(x) # 리스트 길이 확인하기. len 사용한다.

5

In [28]:
y = range(5, 10)
print(y)
print(range(10)) # 시작값을 안넣어주면 0부터 시작한다.
print(list(range(10)))
print(list(y)) # range값 리스트로 확인할때는 list함수 안에 넣어주기.
print(y[0], y[1], y[2], y[3], y[4])

range(5, 10)
range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
5 6 7 8 9


In [29]:
# 튜플 사용하기
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [30]:
# 튜플에서 요소 참조하기(괄호 대신 대괄호 사용하기)
a[1]

2

In [31]:
type(a)

tuple

In [32]:
# 길이가 1인 튜플은 쉼표붙이기
a = (1)
b = (1,)
print(type(a))
print(type(b))

<class 'int'>
<class 'tuple'>


In [33]:
# if문 사용하기
x = 11
if x > 10:
    print('x is')
    print('larger than 10.')
else:
    print('x is smaller than 11')

x is
larger than 10.


In [35]:
x = 9
if x > 10:
    print('x is')
    print('larger than 10.')
else:
    print('x is smaller than 11')

x is smaller than 11


In [36]:
# for 써서 연산 반복하기
for i in [1, 2, 3]:
    print(i)

1
2
3


In [37]:
num = [2, 4, 6, 8, 10]
for i in enumerate(num): # 인덱스값 붙이기
    print(i)
    
# 값이 두개가 나온다.

(0, 2)
(1, 4)
(2, 6)
(3, 8)
(4, 10)


In [38]:
num = [2, 4, 6, 8, 10]
for i in num:
    print(i)

2
4
6
8
10


In [41]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


In [42]:
num = [2, 4, 6, 8, 10]
for i in enumerate(num):
    num[i] = i * 2
print(num)

TypeError: list indices must be integers or slices, not tuple

In [44]:
num = [2, 4, 6, 8, 10]
for i in enumerate(num):
    num[i] = i * 2
print(enumerate(num[i]))

TypeError: list indices must be integers or slices, not tuple

In [47]:
num = [2, 4, 6, 8, 10]
for i in num:
    print(i)

2
4
6
8
10


In [48]:
c = "반갑습니다. 감사합니다. 블로그입니다."
for i in enumerate(c.split()):
    print(i)

(0, '반갑습니다.')
(1, '감사합니다.')
(2, '블로그입니다.')


In [49]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [51]:
type(x)

numpy.ndarray

In [53]:
# array값 수정하기
x[0] = 100
print(x)

[100   2   3]


In [54]:
#ndarray 내용 복사하기

a = np.array([1, 1])
b = a.copy() # a를 복사할때는 b = a라고 쓰는 것이 아닌 .copy 쓰기
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('b=' + str(b))
print('a=' + str(a))

a=[1 1]
b=[1 1]
b=[100   1]
a=[1 1]


In [56]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [57]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [58]:
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [59]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
np.random.rand(2, 3)

array([[0.09081959, 0.63885349, 0.0820565 ],
       [0.50529462, 0.46534589, 0.61649613]])

In [62]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a.reshape(2, 5) # a의 배열을 reshape을 이용하여 2행 5열로 만들어줌.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
# 행렬 사칙연산하기

x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [66]:
# 스칼라 * 행렬
print(10 * x)

[[40 40 40]
 [80 80 80]]


In [69]:
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [73]:
# 행렬 곱 계산하기

v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v)
print(w)
print()
print(v.dot(w))
print()
print(w.dot(v))

[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]

[[14 14]
 [32 32]]

[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


In [75]:
# 슬라이싱 이용하기

x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [76]:
print(x[3:8:2])

[3 5 7]


In [77]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [78]:
# bool 배열 사용하기
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [79]:
x[x > 3]

array([ 5,  8, 13])

In [80]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [82]:
def my_func1():
    print('Hi!')
my_func1()

Hi!


In [83]:
def my_func2(a, b):
    c = a + b
    return c

my_func2(1, 2)

3

In [84]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [89]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:-0.01, std:0.97


In [90]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data) # 세이브
data = [] # 데이터 삭제
print(data)
data = np.load('datafile.npy') # 로드
print(data)

[ 0.04318772 -0.75360456 -0.65942689  1.12865576 -1.20377973]
[]
[ 0.04318772 -0.75360456 -0.65942689  1.12865576 -1.20377973]


In [92]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1 = data1, data2 = data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files) # 저장된 데이터 표시하기
data1 = outfile['data1'] # data1 꺼내기
data2 = outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


In [93]:
d = np.array([[1], [2]])
print(d)

[[1]
 [2]]


In [95]:
print(d.T) # 전치행렬

[[1 2]]


In [97]:
print(2 * d)

[[2]
 [4]]


In [98]:
b = np.array([1, 3])
c = np.array([4, 2])
print(b.dot(c)) # 내적 계산하기

10


In [99]:
a = np.array([1,3])
print(np.linalg.norm(a)) # linalg.norm()로 벡터의 크기를 구할 수 있다.

3.1622776601683795


In [112]:
asia = {'한국', '중국', '일본'}
asia.add('베트남')
asia.add('중국')
asia.remove('일본')
asia.update(["홍콩", '한국', '태국'])
print(asia)

{'중국', '태국', '한국', '홍콩', '베트남'}


In [113]:
square = lambda x: x **2
square(5)

25